export const customKeys = {
  cmd: "left_command",
  ctrl: "left_control",
  esc: "escape",
  hyper: "left_command left_control left_option left_shift",
  l_cmd: "left_command",
  l_ctrl: "left_control",
  l_opt: "left_option",
  l_shift: "left_shift",
  lcmd: "left_command",
  lctrl: "left_control",
  left_cmd: "left_command",
  left_ctrl: "left_control",
  left_opt: "left_option",
  lopt: "left_option",
  lshift: "left_shift",
  opt: "left_option",
  r_cmd: "right_command",
  r_ctrl: "right_control",
  r_opt: "right_option",
  r_shift: "right_shift",
  rcmd: "right_command",
  rctrl: "right_control",
  right_cmd: "right_command",
  right_ctrl: "right_control",
  right_opt: "right_option",
  ropt: "right_option",
  rshift: "right_shift",
  shift: "left_shift",
}
